### PR TITLE
Cascade deletion bugs

### LINKED ISSUE #374: Deleting student with assignment
## What
Deleting a student that is assigned to a project gives an error. 
You can test this via #363 (or on development when this is merged).
The delete student button is present on the select student page as an admin,
it is the trash can icon right next to the student name at the top of the page.

### LINKED ISSUE #375: Deleting coach with status suggestion
## What
Deleting a user with a status suggestion gives an error instead of deleting the user.
You can test this via #350 
Log in as admin, go to users page, click the delete button next to a users name.

### PR DESCRIPTION
**Pull request by NinjaJay**
Closes #374
Closes #375 

This also fixes, if you try to delete a position, it also deletes the assignment.

### CODE REVIEW

**Review by lars-vc — APPROVED** [review]

File: backend/src/main/kotlin/be/osoc/team1/backend/entities/Project.kt [hunk 1]
```diff
@@ -44,11 +50,11 @@ class Position(
  */
 @Entity
 class Assignment(
-    @OneToOne
+    @ManyToOne
```
Comment (MaartenS11) [inline backend/src/main/kotlin/be/osoc/team1/backend/entities/Project.kt:53]: I'm assuming these changes are just to be able to use `mappedBy`?

Comment (NinjaJay) [reply backend/src/main/kotlin/be/osoc/team1/backend/entities/Project.kt:53]: Yes, because in project it's OneToMany assignments, its impossible to have OneToOne in assignment for a project for example. It needs to be opposites.

Comment (MaartenS11) [reply backend/src/main/kotlin/be/osoc/team1/backend/entities/Project.kt:53]: OK then that's fine, there isn't really another way to do it then, so I'm going to resolve this.

**Review by MaartenS11 — APPROVED** [review]
It's a bit sad that Codecov treats some lines as untested when they are just variable definitions, but I don't think we can do much about that.
